networks:
  arig.org:
    name: arig.org
    driver: bridge
    enable_ipv6: False
    ipam:
      config:
        - subnet: 10.60.0.0/24
    driver_opts:
      com.docker.network.bridge.name: "arig.org"
      com.docker.network.bridge.enable_icc: "true"

volumes:
  influx-data:
    name: influxdb.arig.org
  grafana-data:
    name: grafana.arig.org
  pg-data:
    name: pg.arig.org
  reader-logs:
    name: reader-logs.arig.org

services:
  traefik:
    container_name: traefik.arig.org
    image: traefik:v2.11.0
    restart: unless-stopped
    networks:
      arig.org:
        ipv4_address: 10.60.0.10
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.pg.address=:5432
    ports:
      - "80:80"
      - "5432:5432"
    labels:
      - traefik.enable=true
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik.rule=Host(`traefik.arig.org`)
      - traefik.http.routers.traefik.priority=1
      - traefik.http.routers.traefik.entrypoints=web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  influxdb:
    container_name: influxdb.arig.org
    image: influxdb:2.7.5-alpine
    networks:
      - arig.org
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin4ever
      - DOCKER_INFLUXDB_INIT_ORG=arig
      - DOCKER_INFLUXDB_INIT_BUCKET=robots
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-token-connu-pour-auth
    volumes:
      - influx-data:/var/lib/influxdb
    labels:
      - traefik.enable=true
      - traefik.http.routers.influxdb.rule=Host(`influxdb.arig.org`)
      - traefik.http.routers.influxdb.entrypoints=web
    depends_on:
      - traefik

  grafana:
    container_name: grafana.arig.org
    image: grafana/grafana-oss:10.4.1
    networks:
      - arig.org
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.arig.org`)
      - traefik.http.routers.grafana.entrypoints=web
    depends_on:
      - traefik
      - influxdb

  pg:
    container_name: pg.arig.org
    image: postgres:15.3-alpine3.18
    networks:
      - arig.org
    environment:
      - DEBUG=true
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql
    labels:
      - traefik.enable=true
      - traefik.tcp.services.pg.loadbalancer.server.port=5432
      - traefik.tcp.routers.pg.rule=HostSNI(`*`)
      - traefik.tcp.routers.pg.entrypoints=pg
      - traefik.tcp.routers.pg.service=pg
    depends_on:
      - traefik

  pgadmin:
    container_name: pgadmin.arig.org
    image: dpage/pgadmin4
    networks:
      - arig.org
    environment:
      - PGADMIN_DEFAULT_EMAIL=arig@arig.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./conf/pgadmin4-servers.json:/pgadmin4/servers.json
      - ./conf/pgadmin4-pgpass:/pgadmin4/pgpass
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.arig.org`)
      - traefik.http.routers.pgadmin.entrypoints=web
    depends_on:
      - pg

  reader:
    container_name: reader.arig.org
    image: ghcr.io/arig-robotique/robots-reader:latest
    networks:
      - arig.org
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.reader-stripprefix.stripprefix.prefixes=/api
      - traefik.http.routers.reader.rule=Host(`superviseur.arig.org`) && PathPrefix(`/api`)
      - traefik.http.routers.reader.middlewares=reader-stripprefix@docker
      - traefik.http.routers.reader.entrypoints=web
    depends_on:
      - pg
      - grafana
      - influxdb
    volumes:
      - reader-logs:/logs
      - ../../java/robots/nerell-parent/nerell-simulator/logs:/logs-simulateur/nerell
      - ../../java/robots/odin-parent/odin-simulator/logs:/logs-simulateur/odin
      - $SSH_AUTH_SOCK_DEFINED:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  shell:
    container_name: shell.arig.org
    image: fedora:latest
    command: sleep 300
    networks:
      - arig.org
    volumes:
      - $SSH_AUTH_SOCK_DEFINED:/ssh-agent
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  superviseur:
    container_name: superviseur.arig.org
    image: ghcr.io/arig-robotique/robots-supervisor-private:latest
    networks:
      - arig.org
    labels:
      - traefik.enable=true
      - traefik.http.routers.superviseur.rule=Host(`superviseur.arig.org`)
      - traefik.http.routers.superviseur.entrypoints=web
    depends_on:
      - reader
