{
 "title": "Asservissement propulsions",
 "description": "Analyse graphique des datas robots",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "robot_name",
    "label": "Nom du robot",
    "query": "SHOW TAG VALUES ON \"robots\" FROM \"correcteur_pid\" WITH KEY = \"robot\""
   }
  ]
 },
 "panels": [
  { "title": "Odometrie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Encodeurs : Roues propulsion gauche / droite",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "encodeurs",
     "select": [
      [
       { "params": [ "gauche" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "gauche" ], "type": "alias" }
      ],
      [
       { "params": [ "droit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "droite" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "two_wheels_encoders" }
     ]
    }
   ]
  },
  {
   "title": "Encodeurs : Distance / Orientation propulsion",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "encodeurs",
     "select": [
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "distance" ], "type": "alias" }
      ],
      [
       { "params": [ "orientation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "orientation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "two_wheels_encoders" }
     ]
    }
   ]
  },
  { "title": "Rampes vitesse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Distance : Vitesse théorique",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consigne" ], "type": "alias" }
      ],
      [
       { "params": [ "currentVitesse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vitesseCourante théorique" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Orientation : Vitesse théorique",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consigne" ], "type": "alias" }
      ],
      [
       { "params": [ "currentVitesse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vitesseCourante théorique" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Distance : Consigne, Deceleration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "input" ], "type": "alias" }
      ],
      [
       { "params": [ "distanceDeceleration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "distanceDecelaration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Orientation : Consigne, Deceleration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "input" ], "type": "alias" }
      ],
      [
       { "params": [ "distanceDeceleration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "distanceOrientation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Correcteur PID Distance / Orientation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Distance Kp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Distance Ki",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "ki" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Distance Kd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Orientation Kp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Orientation Ki",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "ki" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Orientation Kd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Distance : Consigne, Mesure, Out, Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" }
      ],
      [
       { "params": [ "input" ], "type": "field" }
      ],
      [
       { "params": [ "output" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Orientation : Consigne, Mesure, Out, Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" }
      ],
      [
       { "params": [ "input" ], "type": "field" }
      ],
      [
       { "params": [ "output" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  {
   "title": "Distance : P I D",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "p" ], "type": "field" }
      ],
      [
       { "params": [ "i" ], "type": "field" }
      ],
      [
       { "params": [ "d" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Orientation : P I D",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "p" ], "type": "field" }
      ],
      [
       { "params": [ "i" ], "type": "field" }
      ],
      [
       { "params": [ "d" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "orientation" }
     ]
    }
   ]
  },
  { "title": "Commande moteur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Commande droite / gauche",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "asservissement",
     "select": [
      [
       { "params": [ "mot_d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "droit" ], "type": "alias" }
      ],
      [
       { "params": [ "mot_g" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "gauche" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "polaire" }
     ]
    }
   ]
  }
 ]
}