{
 "title": "Asservissement carousel",
 "description": "Analyse graphique des datas robots",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "robot_name",
    "label": "Nom du robot",
    "query": "SHOW TAG VALUES ON \"robots\" FROM \"correcteur_pid\" WITH KEY = \"robot\""
   }
  ]
 },
 "panels": [
  { "title": "Codeur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Encodeur : carousel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "50ms" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "encodeurs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "value" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Codeur Moteur Carousel_encoder" }
     ]
    }
   ]
  },
  { "title": "Rampes vitesse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Distance : Vitesse théorique",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "50ms" ], "type": "time" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consigne" ], "type": "alias" }
      ],
      [
       { "params": [ "currentVitesse" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "vitesseCourante théorique" ], "type": "alias" }
      ],
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "output" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=", "value": "nerell" }
     ]
    }
   ]
  },
  {
   "title": "Distance : Consigne, Deceleration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "50ms" ], "type": "time" }
     ],
     "measurement": "ramp_vitesse",
     "select": [
      [
       { "params": [ "input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "input" ], "type": "alias" }
      ],
      [
       { "params": [ "distanceDeceleration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "distanceDecelaration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "carousel" }
     ]
    }
   ]
  },
  {
   "title": "Correcteur PID Distance / Orientation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Distance Kp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Distance Ki",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "ki" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Distance Kd",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "kd" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  {
   "title": "Distance : Consigne, Mesure, Out, Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "correcteur_pid",
     "select": [
      [
       { "params": [ "consigne" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consigne" ], "type": "alias" }
      ],
      [
       { "params": [ "input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "input" ], "type": "alias" }
      ],
      [
       { "params": [ "output" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "output" ], "type": "alias" }
      ],
      [
       { "params": [ "error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "error" ], "type": "alias" }
      ],
      [
       { "params": [ "errorSum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "errorSum" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "distance" }
     ]
    }
   ]
  },
  { "title": "Commande moteur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Commande droite / gauche",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "asservissement",
     "select": [
      [
       { "params": [ "mot_d" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "droit" ], "type": "alias" }
      ],
      [
       { "params": [ "mot_g" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "gauche" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "robot", "operator": "=~", "value": "/^$robot_name$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "polaire" }
     ]
    }
   ]
  }
 ]
}