{
 "title": "Infra logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "ARIG tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reader",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"reader\"}"
    }
   ]
  },
  {
   "title": "Superviseur",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"superviseur\"}"
    }
   ]
  },
  { "title": "Infra robot tools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Loki",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"loki\"}"
    }
   ]
  },
  {
   "title": "Influx DB",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"influxdb\"}"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Chronograf",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "{compose_project=\"robot-tools\", compose_service=\"chronograf\"}"
    }
   ]
  }
 ]
}